// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260607234847_NombreDeTuMigracion")]
    partial class NombreDeTuMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Actividad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CanchaId")
                        .HasColumnType("uuid");

                    b.Property<int>("CupoMaximo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TipoReferencia")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId");

                    b.ToTable("Actividad");

                    b.HasDiscriminator<string>("TipoReferencia").HasValue("Actividad");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Asistencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActividadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaHorario")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InscripcionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActividadId");

                    b.HasIndex("InscripcionId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Asistencia");
                });

            modelBuilder.Entity("Domain.Entities.Cancha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<Guid>("TipoCanchaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TipoCanchaId");

                    b.ToTable("Cancha");

                    b.HasData(
                        new
                        {
                            Id = new Guid("af456ce5-6ca1-4808-bae8-1be2e6df8b6b"),
                            Estado = 1,
                            Numero = 1,
                            TipoCanchaId = new Guid("d3c1c19e-61f8-433c-a565-65d8965c1375")
                        },
                        new
                        {
                            Id = new Guid("dc31ae8e-7584-4bab-8b09-837ef9d072b3"),
                            Estado = 1,
                            Numero = 2,
                            TipoCanchaId = new Guid("d3c1c19e-61f8-433c-a565-65d8965c1375")
                        },
                        new
                        {
                            Id = new Guid("2b06a773-fd76-4347-ba9e-2664f884addb"),
                            Estado = 3,
                            Numero = 3,
                            TipoCanchaId = new Guid("66601942-6d1e-4d44-ade9-6cf5215e3af3")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Cobro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MedioPago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MontoFinal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MontoOriginal")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ReferenciaId")
                        .HasColumnType("uuid");

                    b.Property<int>("TipoReferencia")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Cobro");
                });

            modelBuilder.Entity("Domain.Entities.Competencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("ReglamentoInterno")
                        .HasColumnType("text");

                    b.Property<string>("ReglamentoOficial")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Competencia");
                });

            modelBuilder.Entity("Domain.Entities.Descuento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Porcentaje")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Descuento");
                });

            modelBuilder.Entity("Domain.Entities.Inscripcion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompetenciaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReferenciaId")
                        .HasColumnType("uuid");

                    b.Property<int>("TipoInscripcion")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompetenciaId");

                    b.HasIndex("ReferenciaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Inscripcion");
                });

            modelBuilder.Entity("Domain.Entities.Mantenimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CanchaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId");

                    b.ToTable("Mantenimiento");
                });

            modelBuilder.Entity("Domain.Entities.Partido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetenciaId")
                        .HasColumnType("uuid");

                    b.Property<string>("EquipoLocal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EquipoVisitante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GolesLocal")
                        .HasColumnType("integer");

                    b.Property<int>("GolesVisitante")
                        .HasColumnType("integer");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Partido");
                });

            modelBuilder.Entity("Domain.Entities.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoPersona")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.ToTable("Persona");

                    b.HasDiscriminator<string>("TipoPersona").HasValue("PersonaBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Recibo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CobroId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("numeric");

                    b.Property<int>("NumeroComprobante")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CobroId")
                        .IsUnique();

                    b.ToTable("Recibo");
                });

            modelBuilder.Entity("Domain.Entities.Reembolso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CobroId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Monto")
                        .HasColumnType("real");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CobroId");

                    b.ToTable("Reembolso");
                });

            modelBuilder.Entity("Domain.Entities.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CanchaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("Domain.Entities.TipoCancha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<double>("DuracionMax")
                        .HasColumnType("double precision");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("PrecioBaseHora")
                        .HasColumnType("double precision");

                    b.Property<int>("Superficie")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TipoCancha");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d3c1c19e-61f8-433c-a565-65d8965c1375"),
                            Capacidad = 10,
                            DuracionMax = 2.0,
                            Nombre = "Futbol 5",
                            PrecioBaseHora = 5000.0,
                            Superficie = 100
                        },
                        new
                        {
                            Id = new Guid("66601942-6d1e-4d44-ade9-6cf5215e3af3"),
                            Capacidad = 22,
                            DuracionMax = 2.0,
                            Nombre = "Futbol 11",
                            PrecioBaseHora = 5000.0,
                            Superficie = 100
                        });
                });

            modelBuilder.Entity("Domain.Entities.Clase", b =>
                {
                    b.HasBaseType("Domain.Entities.Actividad");

                    b.Property<Guid>("ProfesorId")
                        .HasColumnType("uuid");

                    b.HasIndex("ProfesorId");

                    b.HasDiscriminator().HasValue("Clase");
                });

            modelBuilder.Entity("Domain.Entities.Entrenamiento", b =>
                {
                    b.HasBaseType("Domain.Entities.Actividad");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EntrenadorId")
                        .HasColumnType("uuid");

                    b.HasIndex("EntrenadorId");

                    b.HasDiscriminator().HasValue("Entrenamiento");
                });

            modelBuilder.Entity("Domain.Entities.Entrenador", b =>
                {
                    b.HasBaseType("Domain.Entities.Persona");

                    b.HasDiscriminator().HasValue("Entrenador");
                });

            modelBuilder.Entity("Domain.Entities.Profesor", b =>
                {
                    b.HasBaseType("Domain.Entities.Persona");

                    b.HasDiscriminator().HasValue("Profesor");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.HasBaseType("Domain.Entities.Persona");

                    b.Property<string>("ClerkId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.HasDiscriminator().HasValue("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Actividad", b =>
                {
                    b.HasOne("Domain.Entities.Cancha", "Cancha")
                        .WithMany("Actividades")
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cancha");
                });

            modelBuilder.Entity("Domain.Entities.Asistencia", b =>
                {
                    b.HasOne("Domain.Entities.Actividad", "Actividad")
                        .WithMany()
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Inscripcion", null)
                        .WithMany("Asistencias")
                        .HasForeignKey("InscripcionId");

                    b.HasOne("Domain.Entities.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Domain.Entities.Cancha", b =>
                {
                    b.HasOne("Domain.Entities.TipoCancha", "TipoCancha")
                        .WithMany("Canchas")
                        .HasForeignKey("TipoCanchaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoCancha");
                });

            modelBuilder.Entity("Domain.Entities.Inscripcion", b =>
                {
                    b.HasOne("Domain.Entities.Competencia", null)
                        .WithMany("Inscripciones")
                        .HasForeignKey("CompetenciaId");

                    b.HasOne("Domain.Entities.Actividad", "Actividad")
                        .WithMany("Inscripciones")
                        .HasForeignKey("ReferenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany("Inscripciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Mantenimiento", b =>
                {
                    b.HasOne("Domain.Entities.Cancha", "Cancha")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cancha");
                });

            modelBuilder.Entity("Domain.Entities.Recibo", b =>
                {
                    b.HasOne("Domain.Entities.Cobro", "Cobro")
                        .WithOne("Recibo")
                        .HasForeignKey("Domain.Entities.Recibo", "CobroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cobro");
                });

            modelBuilder.Entity("Domain.Entities.Reembolso", b =>
                {
                    b.HasOne("Domain.Entities.Cobro", null)
                        .WithMany()
                        .HasForeignKey("CobroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Reserva", b =>
                {
                    b.HasOne("Domain.Entities.Cancha", "Cancha")
                        .WithMany("Reservas")
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Clase", b =>
                {
                    b.HasOne("Domain.Entities.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("Domain.Entities.Entrenamiento", b =>
                {
                    b.HasOne("Domain.Entities.Entrenador", "Entrenador")
                        .WithMany()
                        .HasForeignKey("EntrenadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrenador");
                });

            modelBuilder.Entity("Domain.Entities.Actividad", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("Domain.Entities.Cancha", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("Mantenimientos");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Domain.Entities.Cobro", b =>
                {
                    b.Navigation("Recibo");
                });

            modelBuilder.Entity("Domain.Entities.Competencia", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("Domain.Entities.Inscripcion", b =>
                {
                    b.Navigation("Asistencias");
                });

            modelBuilder.Entity("Domain.Entities.TipoCancha", b =>
                {
                    b.Navigation("Canchas");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Inscripciones");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
