// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260605040648_FirstMigrationV3")]
    partial class FirstMigrationV3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Actividad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CanchaId")
                        .HasColumnType("uuid");

                    b.Property<int>("CupoMaximo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId");

                    b.ToTable("Actividad");
                });

            modelBuilder.Entity("Domain.Entities.Asistencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActividadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaHorario")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InscripcionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActividadId");

                    b.HasIndex("InscripcionId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Asistencia");
                });

            modelBuilder.Entity("Domain.Entities.Cancha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<Guid>("TipoCanchaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TipoCanchaId");

                    b.ToTable("Cancha");

                    b.HasData(
                        new
                        {
                            Id = new Guid("74eeb1c3-f642-4f93-bd11-d40485490ce3"),
                            Estado = 1,
                            Numero = 1,
                            TipoCanchaId = new Guid("0a25793a-35b5-4646-bbf8-c2e67b30d8f9")
                        },
                        new
                        {
                            Id = new Guid("081ca5bc-133b-4bd2-b2d8-d024ff97ab02"),
                            Estado = 1,
                            Numero = 2,
                            TipoCanchaId = new Guid("0a25793a-35b5-4646-bbf8-c2e67b30d8f9")
                        },
                        new
                        {
                            Id = new Guid("13083bc7-ac9b-4b67-88f5-58fe37808eeb"),
                            Estado = 3,
                            Numero = 3,
                            TipoCanchaId = new Guid("40e74fc4-f058-4403-907c-bb33062a67db")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Cobro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MedioPago")
                        .HasColumnType("text");

                    b.Property<decimal>("MontoFinal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MontoOriginal")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ReferenciaId")
                        .HasColumnType("uuid");

                    b.Property<int>("TipoReferencia")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Cobro");
                });

            modelBuilder.Entity("Domain.Entities.Descuento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Porcentaje")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Descuento");
                });

            modelBuilder.Entity("Domain.Entities.Inscripcion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActividadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReferenciaId")
                        .HasColumnType("uuid");

                    b.Property<int>("TipoInscripcion")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActividadId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Inscripcion");
                });

            modelBuilder.Entity("Domain.Entities.Mantenimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CanchaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<string>("Motivo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId");

                    b.ToTable("Mantenimiento");
                });

            modelBuilder.Entity("Domain.Entities.Partido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetenciaId")
                        .HasColumnType("uuid");

                    b.Property<string>("EquipoLocal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EquipoVisitante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GolesLocal")
                        .HasColumnType("integer");

                    b.Property<int>("GolesVisitante")
                        .HasColumnType("integer");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Partido");
                });

            modelBuilder.Entity("Domain.Entities.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Persona");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Recibo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CobroId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("numeric");

                    b.Property<int>("NumeroComprobante")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CobroId")
                        .IsUnique();

                    b.ToTable("Recibo");
                });

            modelBuilder.Entity("Domain.Entities.Reembolso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CobroId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Monto")
                        .HasColumnType("real");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Reembolso");
                });

            modelBuilder.Entity("Domain.Entities.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CanchaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("Domain.Entities.TipoCancha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<double>("DuracionMax")
                        .HasColumnType("double precision");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("PrecioBaseHora")
                        .HasColumnType("double precision");

                    b.Property<int>("Superficie")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TipoCancha");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a25793a-35b5-4646-bbf8-c2e67b30d8f9"),
                            Capacidad = 10,
                            DuracionMax = 2.0,
                            Nombre = "Futbol 5",
                            PrecioBaseHora = 5000.0,
                            Superficie = 100
                        },
                        new
                        {
                            Id = new Guid("40e74fc4-f058-4403-907c-bb33062a67db"),
                            Capacidad = 22,
                            DuracionMax = 2.0,
                            Nombre = "Futbol 11",
                            PrecioBaseHora = 5000.0,
                            Superficie = 100
                        });
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.HasBaseType("Domain.Entities.Persona");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Actividad", b =>
                {
                    b.HasOne("Domain.Entities.Cancha", "Cancha")
                        .WithMany("Actividades")
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancha");
                });

            modelBuilder.Entity("Domain.Entities.Asistencia", b =>
                {
                    b.HasOne("Domain.Entities.Actividad", "Actividad")
                        .WithMany()
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Inscripcion", null)
                        .WithMany("Asistencias")
                        .HasForeignKey("InscripcionId");

                    b.HasOne("Domain.Entities.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Domain.Entities.Cancha", b =>
                {
                    b.HasOne("Domain.Entities.TipoCancha", "TipoCancha")
                        .WithMany("Canchas")
                        .HasForeignKey("TipoCanchaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoCancha");
                });

            modelBuilder.Entity("Domain.Entities.Inscripcion", b =>
                {
                    b.HasOne("Domain.Entities.Actividad", null)
                        .WithMany("Inscripciones")
                        .HasForeignKey("ActividadId");

                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Mantenimiento", b =>
                {
                    b.HasOne("Domain.Entities.Cancha", "Cancha")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancha");
                });

            modelBuilder.Entity("Domain.Entities.Recibo", b =>
                {
                    b.HasOne("Domain.Entities.Cobro", "Cobro")
                        .WithOne("Recibo")
                        .HasForeignKey("Domain.Entities.Recibo", "CobroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cobro");
                });

            modelBuilder.Entity("Domain.Entities.Reserva", b =>
                {
                    b.HasOne("Domain.Entities.Cancha", "Cancha")
                        .WithMany("Reservas")
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Actividad", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("Domain.Entities.Cancha", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("Mantenimientos");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Domain.Entities.Cobro", b =>
                {
                    b.Navigation("Recibo");
                });

            modelBuilder.Entity("Domain.Entities.Inscripcion", b =>
                {
                    b.Navigation("Asistencias");
                });

            modelBuilder.Entity("Domain.Entities.TipoCancha", b =>
                {
                    b.Navigation("Canchas");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
